export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  FILTER_PRODUCT_BY_CATEGORY: "FILTER_PRODUCT_BY_CATEGORY",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
};

export const SidebarType = {
  SHOW_SIDEBAR: "SHOW_SIDEBAR",
  HIDE_SIDEBAR: "HIDE_SIDEBAR",
};

export const ReviewType = {
  FETCH_REVIEWS: "FETCH_REVIEWS",
  FETCH_LIMITED_REVIEWS: "FETCH_LIMITED_REVIEWS",
  REMOVE_LIMITED_REVIEWS: "REMOVE_LIMITED_REVIEWS",
  CREATE_REVIEW: "CREATE_REVIEW",
};
